### ISSUE TITLE
Version Release?

### ISSUE THREAD

**Issue by davidedelvento** [jswhit/gfstonc#1]
I've noticed from setup.py that this code is called v0.0.1 -- any plan to make that a release? I've been asked to install gfstonc on a server, and it is our policy to install only released software, so we can easily identify which version we are running.

**Comment by jswhit** [comment]
I made a version 0.0.1 release:

https://github.com/jswhit/gfstonc/releases

**Comment by davidedelvento** [comment]
Great thanks!
